'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Converter.Properties


	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	<System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")> _
	Friend NotInheritable Partial Class Settings
		Inherits Global.System.Configuration.ApplicationSettingsBase

		Private Shared defaultInstance As Settings = (CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings())), Settings))

		Public Shared ReadOnly Property [Default]() As Settings
			Get
				Return defaultInstance
			End Get
		End Property

		<System.Configuration.ApplicationScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public ReadOnly Property SQLServerAddress() As String
			Get
				Return (CType((Me("SQLServerAddress")), String))
			End Get
		End Property

		<System.Configuration.ApplicationScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.DefaultSettingValueAttribute("")> _
		Public ReadOnly Property DatabasePath() As String
			Get
				Return (CType((Me("DatabasePath")), String))
			End Get
		End Property

		<System.Configuration.ApplicationScopedSettingAttribute> _
		<System.Diagnostics.DebuggerNonUserCodeAttribute> _
		<System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString)> _
		<System.Configuration.DefaultSettingValueAttribute("Data Source=10.10.32.10;Initial Catalog=TIMETABLE_JAN2015;Persist Security Info=T" + "rue;User ID=sa;Password=12345")> _
		Public ReadOnly Property myconn() As String
			Get
				Return (CType((Me("myconn")), String))
			End Get
		End Property
	End Class
End Namespace