'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="TIMETABLE_JAN2014.MDF")>  _
Partial Public Class DataClasses1DataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.TimeTableManager.My.MySettings.Default.eCollegeConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property M_Time_Tables() As System.Data.Linq.Table(Of M_Time_Table)
		Get
			Return Me.GetTable(Of M_Time_Table)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.M_Time_Table")>  _
Partial Public Class M_Time_Table
	
	Private _TimeTableId As Integer
	
	Private _Section_Id As Integer
	
	Private _TT_Day As Integer
	
	Private _TT_Period As Integer
	
	Private _CSF_Id As Integer
	
	Private _Room_Id As System.Nullable(Of Integer)
	
	Private _Batch_Id As Integer
	
	Private _Section_Group_Id As Long
	
	Private _MergeCSF As Integer
	
	Private _ActivityTag As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TimeTableId", DbType:="Int NOT NULL")>  _
	Public Property TimeTableId() As Integer
		Get
			Return Me._TimeTableId
		End Get
		Set
			If ((Me._TimeTableId = value)  _
						= false) Then
				Me._TimeTableId = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Section_Id", DbType:="Int NOT NULL")>  _
	Public Property Section_Id() As Integer
		Get
			Return Me._Section_Id
		End Get
		Set
			If ((Me._Section_Id = value)  _
						= false) Then
				Me._Section_Id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TT_Day", DbType:="Int NOT NULL")>  _
	Public Property TT_Day() As Integer
		Get
			Return Me._TT_Day
		End Get
		Set
			If ((Me._TT_Day = value)  _
						= false) Then
				Me._TT_Day = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TT_Period", DbType:="Int NOT NULL")>  _
	Public Property TT_Period() As Integer
		Get
			Return Me._TT_Period
		End Get
		Set
			If ((Me._TT_Period = value)  _
						= false) Then
				Me._TT_Period = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CSF_Id", DbType:="Int NOT NULL")>  _
	Public Property CSF_Id() As Integer
		Get
			Return Me._CSF_Id
		End Get
		Set
			If ((Me._CSF_Id = value)  _
						= false) Then
				Me._CSF_Id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Room_Id", DbType:="Int")>  _
	Public Property Room_Id() As System.Nullable(Of Integer)
		Get
			Return Me._Room_Id
		End Get
		Set
			If (Me._Room_Id.Equals(value) = false) Then
				Me._Room_Id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Batch_Id", DbType:="Int NOT NULL")>  _
	Public Property Batch_Id() As Integer
		Get
			Return Me._Batch_Id
		End Get
		Set
			If ((Me._Batch_Id = value)  _
						= false) Then
				Me._Batch_Id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Section_Group_Id", DbType:="BigInt NOT NULL")>  _
	Public Property Section_Group_Id() As Long
		Get
			Return Me._Section_Group_Id
		End Get
		Set
			If ((Me._Section_Group_Id = value)  _
						= false) Then
				Me._Section_Group_Id = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MergeCSF", DbType:="Int NOT NULL")>  _
	Public Property MergeCSF() As Integer
		Get
			Return Me._MergeCSF
		End Get
		Set
			If ((Me._MergeCSF = value)  _
						= false) Then
				Me._MergeCSF = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ActivityTag", DbType:="VarChar(10)")>  _
	Public Property ActivityTag() As String
		Get
			Return Me._ActivityTag
		End Get
		Set
			If (String.Equals(Me._ActivityTag, value) = false) Then
				Me._ActivityTag = value
			End If
		End Set
	End Property
End Class
